" Custom Configuration
inoremap jj <Esc>
inoremap ,w <Esc>:w<cr>
noremap ,w :w<cr>

" Basic configs
syntax on
set nocompatible
set encoding=utf-8
set showmode
set number
set relativenumber
set mouse=a
set autoindent
set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4
filetype indent on
" search
set showmatch
set hlsearch
set incsearch

